# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ros_iop_ocu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.robotlistTreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.robotlistTreeWidget.setGeometry(QtCore.QRect(20, 20, 251, 431))
        self.robotlistTreeWidget.setObjectName("robotlistTreeWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(280, 20, 551, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.platform = QtWidgets.QWidget()
        self.platform.setObjectName("platform")
        self.serviceTreeWidget = QtWidgets.QTreeWidget(self.platform)
        self.serviceTreeWidget.setGeometry(QtCore.QRect(20, 140, 491, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serviceTreeWidget.sizePolicy().hasHeightForWidth())
        self.serviceTreeWidget.setSizePolicy(sizePolicy)
        self.serviceTreeWidget.setLineWidth(1)
        self.serviceTreeWidget.setObjectName("serviceTreeWidget")
        self.configTableWidget = QtWidgets.QTableWidget(self.platform)
        self.configTableWidget.setGeometry(QtCore.QRect(20, 0, 211, 131))
        self.configTableWidget.setObjectName("configTableWidget")
        self.configTableWidget.setColumnCount(2)
        self.configTableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.configTableWidget.setItem(2, 1, item)
        self.senserTableWidget = QtWidgets.QTableWidget(self.platform)
        self.senserTableWidget.setGeometry(QtCore.QRect(270, 0, 241, 121))
        self.senserTableWidget.setObjectName("senserTableWidget")
        self.senserTableWidget.setColumnCount(2)
        self.senserTableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.senserTableWidget.setItem(2, 1, item)
        self.tabWidget.addTab(self.platform, "")
        self.mission = QtWidgets.QWidget()
        self.mission.setObjectName("mission")
        self.selectedRobotNmae = QtWidgets.QLabel(self.mission)
        self.selectedRobotNmae.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.selectedRobotNmae.setFont(font)
        self.selectedRobotNmae.setObjectName("selectedRobotNmae")
        self.robotnamelineEdit = QtWidgets.QLineEdit(self.mission)
        self.robotnamelineEdit.setGeometry(QtCore.QRect(120, 20, 231, 31))
        self.robotnamelineEdit.setMaxLength(32761)
        self.robotnamelineEdit.setReadOnly(False)
        self.robotnamelineEdit.setObjectName("robotnamelineEdit")
        self.okButton = QtWidgets.QPushButton(self.mission)
        self.okButton.setGeometry(QtCore.QRect(120, 50, 101, 31))
        self.okButton.setObjectName("okButton")
        self.cancelcontrolButton = QtWidgets.QPushButton(self.mission)
        self.cancelcontrolButton.setGeometry(QtCore.QRect(250, 50, 101, 31))
        self.cancelcontrolButton.setObjectName("cancelcontrolButton")
        self.frontButton = QtWidgets.QPushButton(self.mission)
        self.frontButton.setGeometry(QtCore.QRect(140, 130, 71, 61))
        self.frontButton.setObjectName("frontButton")
        self.rightButton = QtWidgets.QPushButton(self.mission)
        self.rightButton.setGeometry(QtCore.QRect(210, 190, 71, 61))
        self.rightButton.setObjectName("rightButton")
        self.backButton = QtWidgets.QPushButton(self.mission)
        self.backButton.setGeometry(QtCore.QRect(140, 250, 71, 61))
        self.backButton.setObjectName("backButton")
        self.leftButton = QtWidgets.QPushButton(self.mission)
        self.leftButton.setGeometry(QtCore.QRect(70, 190, 71, 61))
        self.leftButton.setObjectName("leftButton")
        self.linearverticalSlider = QtWidgets.QSlider(self.mission)
        self.linearverticalSlider.setGeometry(QtCore.QRect(350, 120, 51, 221))
        self.linearverticalSlider.setMaximum(70)
        self.linearverticalSlider.setSingleStep(5)
        self.linearverticalSlider.setSliderPosition(30)
        self.linearverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.linearverticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.linearverticalSlider.setTickInterval(2)
        self.linearverticalSlider.setObjectName("linearverticalSlider")
        self.linearplusButton = QtWidgets.QPushButton(self.mission)
        self.linearplusButton.setGeometry(QtCore.QRect(320, 120, 31, 27))
        self.linearplusButton.setObjectName("linearplusButton")
        self.linearsubButton = QtWidgets.QPushButton(self.mission)
        self.linearsubButton.setGeometry(QtCore.QRect(320, 310, 31, 27))
        self.linearsubButton.setObjectName("linearsubButton")
        self.linarvelocitylabel = QtWidgets.QLabel(self.mission)
        self.linarvelocitylabel.setGeometry(QtCore.QRect(350, 90, 67, 31))
        self.linarvelocitylabel.setObjectName("linarvelocitylabel")
        self.linearshowlabel = QtWidgets.QLabel(self.mission)
        self.linearshowlabel.setGeometry(QtCore.QRect(350, 350, 61, 31))
        self.linearshowlabel.setObjectName("linearshowlabel")
        self.angularlabel = QtWidgets.QLabel(self.mission)
        self.angularlabel.setGeometry(QtCore.QRect(470, 90, 67, 31))
        self.angularlabel.setObjectName("angularlabel")
        self.angularshowlabel = QtWidgets.QLabel(self.mission)
        self.angularshowlabel.setGeometry(QtCore.QRect(460, 350, 71, 31))
        self.angularshowlabel.setObjectName("angularshowlabel")
        self.angularsubButton = QtWidgets.QPushButton(self.mission)
        self.angularsubButton.setGeometry(QtCore.QRect(440, 310, 31, 27))
        self.angularsubButton.setObjectName("angularsubButton")
        self.angularverticalSlider = QtWidgets.QSlider(self.mission)
        self.angularverticalSlider.setGeometry(QtCore.QRect(470, 120, 51, 221))
        self.angularverticalSlider.setMaximum(70)
        self.angularverticalSlider.setSingleStep(5)
        self.angularverticalSlider.setSliderPosition(30)
        self.angularverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.angularverticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.angularverticalSlider.setTickInterval(2)
        self.angularverticalSlider.setObjectName("angularverticalSlider")
        self.angularplusButton = QtWidgets.QPushButton(self.mission)
        self.angularplusButton.setGeometry(QtCore.QRect(440, 120, 31, 27))
        self.angularplusButton.setObjectName("angularplusButton")
        self.tabWidget.addTab(self.mission, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.multirobotplainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.multirobotplainTextEdit.setGeometry(QtCore.QRect(100, 10, 391, 81))
        self.multirobotplainTextEdit.setObjectName("multirobotplainTextEdit")
        self.frontmultirobotButton = QtWidgets.QPushButton(self.tab)
        self.frontmultirobotButton.setGeometry(QtCore.QRect(240, 180, 71, 61))
        self.frontmultirobotButton.setObjectName("frontmultirobotButton")
        self.rightmultirobotButton = QtWidgets.QPushButton(self.tab)
        self.rightmultirobotButton.setGeometry(QtCore.QRect(310, 240, 71, 61))
        self.rightmultirobotButton.setObjectName("rightmultirobotButton")
        self.backmultirobotButton = QtWidgets.QPushButton(self.tab)
        self.backmultirobotButton.setGeometry(QtCore.QRect(240, 300, 71, 61))
        self.backmultirobotButton.setObjectName("backmultirobotButton")
        self.leftmultirobotButton = QtWidgets.QPushButton(self.tab)
        self.leftmultirobotButton.setGeometry(QtCore.QRect(170, 240, 71, 61))
        self.leftmultirobotButton.setObjectName("leftmultirobotButton")
        self.linearmultirobotsubButton = QtWidgets.QPushButton(self.tab)
        self.linearmultirobotsubButton.setGeometry(QtCore.QRect(30, 330, 31, 27))
        self.linearmultirobotsubButton.setObjectName("linearmultirobotsubButton")
        self.linearmultirobotplusButton = QtWidgets.QPushButton(self.tab)
        self.linearmultirobotplusButton.setGeometry(QtCore.QRect(30, 140, 31, 27))
        self.linearmultirobotplusButton.setObjectName("linearmultirobotplusButton")
        self.linearmultirobotverticalSlider = QtWidgets.QSlider(self.tab)
        self.linearmultirobotverticalSlider.setGeometry(QtCore.QRect(60, 140, 51, 221))
        self.linearmultirobotverticalSlider.setMaximum(70)
        self.linearmultirobotverticalSlider.setSingleStep(5)
        self.linearmultirobotverticalSlider.setSliderPosition(30)
        self.linearmultirobotverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.linearmultirobotverticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.linearmultirobotverticalSlider.setTickInterval(2)
        self.linearmultirobotverticalSlider.setObjectName("linearmultirobotverticalSlider")
        self.linarmultirobotvelocitylabel = QtWidgets.QLabel(self.tab)
        self.linarmultirobotvelocitylabel.setGeometry(QtCore.QRect(60, 110, 67, 31))
        self.linarmultirobotvelocitylabel.setObjectName("linarmultirobotvelocitylabel")
        self.linearmultirobotshowlabel = QtWidgets.QLabel(self.tab)
        self.linearmultirobotshowlabel.setGeometry(QtCore.QRect(60, 370, 61, 31))
        self.linearmultirobotshowlabel.setObjectName("linearmultirobotshowlabel")
        self.angularmultirobotshowlabel = QtWidgets.QLabel(self.tab)
        self.angularmultirobotshowlabel.setGeometry(QtCore.QRect(470, 370, 81, 31))
        self.angularmultirobotshowlabel.setObjectName("angularmultirobotshowlabel")
        self.angularmultirobotplusButton = QtWidgets.QPushButton(self.tab)
        self.angularmultirobotplusButton.setGeometry(QtCore.QRect(440, 140, 31, 27))
        self.angularmultirobotplusButton.setObjectName("angularmultirobotplusButton")
        self.angularmultirobotlabel = QtWidgets.QLabel(self.tab)
        self.angularmultirobotlabel.setGeometry(QtCore.QRect(470, 110, 67, 31))
        self.angularmultirobotlabel.setObjectName("angularmultirobotlabel")
        self.angularmultirobotsubButton = QtWidgets.QPushButton(self.tab)
        self.angularmultirobotsubButton.setGeometry(QtCore.QRect(440, 330, 31, 27))
        self.angularmultirobotsubButton.setObjectName("angularmultirobotsubButton")
        self.angularmultirobotverticalSlider = QtWidgets.QSlider(self.tab)
        self.angularmultirobotverticalSlider.setGeometry(QtCore.QRect(470, 140, 51, 221))
        self.angularmultirobotverticalSlider.setMaximum(70)
        self.angularmultirobotverticalSlider.setSingleStep(5)
        self.angularmultirobotverticalSlider.setSliderPosition(30)
        self.angularmultirobotverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.angularmultirobotverticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.angularmultirobotverticalSlider.setTickInterval(2)
        self.angularmultirobotverticalSlider.setObjectName("angularmultirobotverticalSlider")
        self.multirobotcancelcontrolButton = QtWidgets.QPushButton(self.tab)
        self.multirobotcancelcontrolButton.setGeometry(QtCore.QRect(300, 120, 101, 31))
        self.multirobotcancelcontrolButton.setObjectName("multirobotcancelcontrolButton")
        self.multirobotokButton = QtWidgets.QPushButton(self.tab)
        self.multirobotokButton.setGeometry(QtCore.QRect(170, 120, 101, 31))
        self.multirobotokButton.setObjectName("multirobotokButton")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(20, 89, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab, "")
        self.mutileControl = QtWidgets.QWidget()
        self.mutileControl.setObjectName("mutileControl")
        self.groupBox3_2 = QtWidgets.QGroupBox(self.mutileControl)
        self.groupBox3_2.setGeometry(QtCore.QRect(40, 230, 471, 91))
        self.groupBox3_2.setTitle("")
        self.groupBox3_2.setObjectName("groupBox3_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox3_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox3_2)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_8.setObjectName("label_8")
        self.ugvLineEdit_2 = QtWidgets.QLineEdit(self.groupBox3_2)
        self.ugvLineEdit_2.setGeometry(QtCore.QRect(40, 40, 113, 20))
        self.ugvLineEdit_2.setObjectName("ugvLineEdit_2")
        self.uavLineEdit_2 = QtWidgets.QLineEdit(self.groupBox3_2)
        self.uavLineEdit_2.setGeometry(QtCore.QRect(40, 10, 111, 20))
        self.uavLineEdit_2.setObjectName("uavLineEdit_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox3_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 10, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.collaborationControlButton_2 = QtWidgets.QPushButton(self.groupBox3_2)
        self.collaborationControlButton_2.setGeometry(QtCore.QRect(340, 40, 75, 23))
        self.collaborationControlButton_2.setObjectName("collaborationControlButton_2")
        self.collaborationOkButton_2 = QtWidgets.QPushButton(self.groupBox3_2)
        self.collaborationOkButton_2.setGeometry(QtCore.QRect(220, 40, 75, 23))
        self.collaborationOkButton_2.setObjectName("collaborationOkButton_2")
        self.groupBox2_2 = QtWidgets.QGroupBox(self.mutileControl)
        self.groupBox2_2.setGeometry(QtCore.QRect(40, 90, 471, 91))
        self.groupBox2_2.setTitle("")
        self.groupBox2_2.setObjectName("groupBox2_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox2_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 21, 21))
        self.label_9.setObjectName("label_9")
        self.mainRobotLineEdit_2 = QtWidgets.QLineEdit(self.groupBox2_2)
        self.mainRobotLineEdit_2.setGeometry(QtCore.QRect(50, 20, 113, 20))
        self.mainRobotLineEdit_2.setObjectName("mainRobotLineEdit_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox2_2)
        self.label_10.setGeometry(QtCore.QRect(190, 20, 21, 16))
        self.label_10.setObjectName("label_10")
        self.slaveRobotLineEdit_2 = QtWidgets.QLineEdit(self.groupBox2_2)
        self.slaveRobotLineEdit_2.setGeometry(QtCore.QRect(222, 20, 191, 20))
        self.slaveRobotLineEdit_2.setObjectName("slaveRobotLineEdit_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox2_2)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_11.setObjectName("label_11")
        self.formationComboBox_2 = QtWidgets.QComboBox(self.groupBox2_2)
        self.formationComboBox_2.setGeometry(QtCore.QRect(50, 50, 131, 22))
        self.formationComboBox_2.setObjectName("formationComboBox_2")
        self.formationComboBox_2.addItem("")
        self.formationComboBox_2.addItem("")
        self.formationOkButton_2 = QtWidgets.QPushButton(self.groupBox2_2)
        self.formationOkButton_2.setGeometry(QtCore.QRect(220, 50, 75, 23))
        self.formationOkButton_2.setObjectName("formationOkButton_2")
        self.formationControlButton_2 = QtWidgets.QPushButton(self.groupBox2_2)
        self.formationControlButton_2.setGeometry(QtCore.QRect(340, 50, 75, 23))
        self.formationControlButton_2.setObjectName("formationControlButton_2")
        self.formationRadioButton_2 = QtWidgets.QRadioButton(self.mutileControl)
        self.formationRadioButton_2.setGeometry(QtCore.QRect(40, 70, 89, 16))
        self.formationRadioButton_2.setObjectName("formationRadioButton_2")
        self.collaborationRadioButton_2 = QtWidgets.QRadioButton(self.mutileControl)
        self.collaborationRadioButton_2.setGeometry(QtCore.QRect(40, 210, 89, 16))
        self.collaborationRadioButton_2.setObjectName("collaborationRadioButton_2")
        self.tabWidget.addTab(self.mutileControl, "")
        self.showimageTab = QtWidgets.QWidget()
        self.showimageTab.setObjectName("showimageTab")
        self.showimagelabel = QtWidgets.QLabel(self.showimageTab)
        self.showimagelabel.setGeometry(QtCore.QRect(30, 20, 501, 311))
        self.showimagelabel.setText("")
        self.showimagelabel.setObjectName("showimagelabel")
        self.pushButton = QtWidgets.QPushButton(self.showimageTab)
        self.pushButton.setGeometry(QtCore.QRect(300, 360, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.pointcloudButton = QtWidgets.QPushButton(self.showimageTab)
        self.pointcloudButton.setGeometry(QtCore.QRect(50, 360, 181, 31))
        self.pointcloudButton.setObjectName("pointcloudButton")
        self.tabWidget.addTab(self.showimageTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.aubolabel = QtWidgets.QLabel(self.tab_2)
        self.aubolabel.setGeometry(QtCore.QRect(30, 30, 221, 321))
        self.aubolabel.setText("")
        self.aubolabel.setObjectName("aubolabel")
        self.basepushButton = QtWidgets.QPushButton(self.tab_2)
        self.basepushButton.setGeometry(QtCore.QRect(300, 80, 99, 41))
        self.basepushButton.setObjectName("basepushButton")
        self.shouderpushButton = QtWidgets.QPushButton(self.tab_2)
        self.shouderpushButton.setGeometry(QtCore.QRect(300, 200, 99, 41))
        self.shouderpushButton.setObjectName("shouderpushButton")
        self.elbowpushButton = QtWidgets.QPushButton(self.tab_2)
        self.elbowpushButton.setGeometry(QtCore.QRect(300, 140, 99, 41))
        self.elbowpushButton.setObjectName("elbowpushButton")
        self.wrist1pushButton = QtWidgets.QPushButton(self.tab_2)
        self.wrist1pushButton.setGeometry(QtCore.QRect(430, 80, 99, 41))
        self.wrist1pushButton.setObjectName("wrist1pushButton")
        self.wrist2pushButton = QtWidgets.QPushButton(self.tab_2)
        self.wrist2pushButton.setGeometry(QtCore.QRect(430, 140, 99, 41))
        self.wrist2pushButton.setObjectName("wrist2pushButton")
        self.wrist3pushButton = QtWidgets.QPushButton(self.tab_2)
        self.wrist3pushButton.setGeometry(QtCore.QRect(430, 200, 99, 41))
        self.wrist3pushButton.setObjectName("wrist3pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.translineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.translineEdit.setGeometry(QtCore.QRect(380, 10, 161, 27))
        self.translineEdit.setObjectName("translineEdit")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(300, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.maxspeedlineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.maxspeedlineEdit.setGeometry(QtCore.QRect(380, 40, 161, 27))
        self.maxspeedlineEdit.setObjectName("maxspeedlineEdit")
        self.aubopluspushButton = QtWidgets.QPushButton(self.tab_2)
        self.aubopluspushButton.setGeometry(QtCore.QRect(330, 250, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.aubopluspushButton.setFont(font)
        self.aubopluspushButton.setObjectName("aubopluspushButton")
        self.aubosubpushButton = QtWidgets.QPushButton(self.tab_2)
        self.aubosubpushButton.setGeometry(QtCore.QRect(430, 250, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.aubosubpushButton.setFont(font)
        self.aubosubpushButton.setObjectName("aubosubpushButton")
        self.currentangularlineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.currentangularlineEdit.setGeometry(QtCore.QRect(380, 340, 161, 27))
        self.currentangularlineEdit.setObjectName("currentangularlineEdit")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(300, 340, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_2, "")
        self.logtabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.logtabWidget.setGeometry(QtCore.QRect(20, 460, 821, 221))
        self.logtabWidget.setObjectName("logtabWidget")
        self.logshowTabwidget = QtWidgets.QWidget()
        self.logshowTabwidget.setObjectName("logshowTabwidget")
        self.logtextEdit = QtWidgets.QTextEdit(self.logshowTabwidget)
        self.logtextEdit.setGeometry(QtCore.QRect(0, 0, 821, 211))
        self.logtextEdit.setObjectName("logtextEdit")
        self.logtabWidget.addTab(self.logshowTabwidget, "")
        self.tabWidget.raise_()
        self.robotlistTreeWidget.raise_()
        self.logtabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.logtabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.robotlistTreeWidget.headerItem().setText(0, _translate("MainWindow", "平台列表"))
        self.serviceTreeWidget.headerItem().setText(0, _translate("MainWindow", "服务列表                                                              "))
        self.serviceTreeWidget.headerItem().setText(1, _translate("MainWindow", "状态"))
        self.serviceTreeWidget.headerItem().setText(2, _translate("MainWindow", "操作"))
        item = self.configTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.configTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.configTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.configTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "项目"))
        item = self.configTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "详情"))
        __sortingEnabled = self.configTableWidget.isSortingEnabled()
        self.configTableWidget.setSortingEnabled(False)
        item = self.configTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "型号"))
        item = self.configTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "操作系统"))
        item = self.configTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "ROS"))
        self.configTableWidget.setSortingEnabled(__sortingEnabled)
        item = self.senserTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.senserTableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.senserTableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.senserTableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.senserTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "载荷"))
        item = self.senserTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "详情"))
        __sortingEnabled = self.senserTableWidget.isSortingEnabled()
        self.senserTableWidget.setSortingEnabled(False)
        item = self.senserTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "激光雷达"))
        item = self.senserTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "LIDAS"))
        item = self.senserTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "图传"))
        item = self.senserTableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "YIKUN"))
        item = self.senserTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "定位"))
        item = self.senserTableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "RTK"))
        self.senserTableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.platform), _translate("MainWindow", "平台管理"))
        self.selectedRobotNmae.setText(_translate("MainWindow", "选择设备名："))
        self.robotnamelineEdit.setText(_translate("MainWindow", "Bulldog"))
        self.okButton.setText(_translate("MainWindow", "确认控制"))
        self.cancelcontrolButton.setText(_translate("MainWindow", "取消控制"))
        self.frontButton.setText(_translate("MainWindow", "前进"))
        self.rightButton.setText(_translate("MainWindow", "右转"))
        self.backButton.setText(_translate("MainWindow", "后退"))
        self.leftButton.setText(_translate("MainWindow", "左转"))
        self.linearplusButton.setText(_translate("MainWindow", "+"))
        self.linearsubButton.setText(_translate("MainWindow", "-"))
        self.linarvelocitylabel.setText(_translate("MainWindow", "线速度"))
        self.linearshowlabel.setText(_translate("MainWindow", "１m/s"))
        self.angularlabel.setText(_translate("MainWindow", "角速度"))
        self.angularshowlabel.setText(_translate("MainWindow", "１rad/s"))
        self.angularsubButton.setText(_translate("MainWindow", "-"))
        self.angularplusButton.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission), _translate("MainWindow", "单体控制"))
        self.label.setText(_translate("MainWindow", "设备列表"))
        self.frontmultirobotButton.setText(_translate("MainWindow", "前进"))
        self.rightmultirobotButton.setText(_translate("MainWindow", "右转"))
        self.backmultirobotButton.setText(_translate("MainWindow", "后退"))
        self.leftmultirobotButton.setText(_translate("MainWindow", "左转"))
        self.linearmultirobotsubButton.setText(_translate("MainWindow", "-"))
        self.linearmultirobotplusButton.setText(_translate("MainWindow", "+"))
        self.linarmultirobotvelocitylabel.setText(_translate("MainWindow", "线速度"))
        self.linearmultirobotshowlabel.setText(_translate("MainWindow", "１m/s"))
        self.angularmultirobotshowlabel.setText(_translate("MainWindow", "１rad/s"))
        self.angularmultirobotplusButton.setText(_translate("MainWindow", "+"))
        self.angularmultirobotlabel.setText(_translate("MainWindow", "角速度"))
        self.angularmultirobotsubButton.setText(_translate("MainWindow", "-"))
        self.multirobotcancelcontrolButton.setText(_translate("MainWindow", "取消控制"))
        self.multirobotokButton.setText(_translate("MainWindow", "确认控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "群体控制"))
        self.label_7.setText(_translate("MainWindow", "空："))
        self.label_8.setText(_translate("MainWindow", "地："))
        self.ugvLineEdit_2.setText(_translate("MainWindow", "Bulldog"))
        self.uavLineEdit_2.setText(_translate("MainWindow", "M210"))
        self.lineEdit_8.setText(_translate("MainWindow", "M210"))
        self.collaborationControlButton_2.setText(_translate("MainWindow", "控制"))
        self.collaborationOkButton_2.setText(_translate("MainWindow", "确定"))
        self.label_9.setText(_translate("MainWindow", "主："))
        self.mainRobotLineEdit_2.setText(_translate("MainWindow", "Bulldog"))
        self.label_10.setText(_translate("MainWindow", "从："))
        self.slaveRobotLineEdit_2.setText(_translate("MainWindow", "TB-1、TB-2"))
        self.label_11.setText(_translate("MainWindow", "队形："))
        self.formationComboBox_2.setItemText(0, _translate("MainWindow", "纵队突击"))
        self.formationComboBox_2.setItemText(1, _translate("MainWindow", "箭头队形"))
        self.formationOkButton_2.setText(_translate("MainWindow", "确定"))
        self.formationControlButton_2.setText(_translate("MainWindow", "控制"))
        self.formationRadioButton_2.setText(_translate("MainWindow", "编队控制"))
        self.collaborationRadioButton_2.setText(_translate("MainWindow", "空地协同"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mutileControl), _translate("MainWindow", "任务管理"))
        self.pushButton.setText(_translate("MainWindow", "画面显示"))
        self.pointcloudButton.setText(_translate("MainWindow", "点云显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.showimageTab), _translate("MainWindow", "图传画面"))
        self.basepushButton.setText(_translate("MainWindow", "基座/base"))
        self.shouderpushButton.setText(_translate("MainWindow", "肩部/shoulder"))
        self.elbowpushButton.setText(_translate("MainWindow", "肘部/Elbow"))
        self.wrist1pushButton.setText(_translate("MainWindow", "腕部/Wrist1"))
        self.wrist2pushButton.setText(_translate("MainWindow", "腕部/Wrist2"))
        self.wrist3pushButton.setText(_translate("MainWindow", "腕部/Wrist3"))
        self.label_3.setText(_translate("MainWindow", "运动范围："))
        self.label_4.setText(_translate("MainWindow", "最大速度："))
        self.aubopluspushButton.setText(_translate("MainWindow", "＋"))
        self.aubosubpushButton.setText(_translate("MainWindow", "－"))
        self.label_20.setText(_translate("MainWindow", "当前角度："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "机械臂控制"))
        self.logtabWidget.setTabText(self.logtabWidget.indexOf(self.logshowTabwidget), _translate("MainWindow", "日志信息"))

